version: "3.9"

services:
  web:
    image: python:3.8.5
    build: .
    #network_mode: host
    ports:
      #- "8000:8000"
      - "5001:5001"
      #- "443:443"
      #- "80:80"
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: postgres
      DB_USER: postgres
      DB_PASSWORD: example
    volumes:
      - .:/app

  db:
    image: postgres:13
    volumes:
      - db-data:/var/lib/postgresql/data/
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example
      POSTGRES_DB: postgres

volumes:
  db-data: